/** Banques de contenus du module fun (français). */

export const EIGHT_BALL = [
  'C\'est certain.', 'C\'est décidément ainsi.', 'Sans aucun doute.', 'Oui, absolument.', 'Tu peux compter dessus.',
  'D\'après moi, oui.', 'Très probablement.', 'Les perspectives sont bonnes.', 'Oui.', 'Les signes indiquent que oui.',
  'Réponse floue, réessaie.', 'Redemande plus tard.', 'Mieux vaut ne pas te le dire maintenant.', 'Impossible de prédire pour l\'instant.', 'Concentre-toi et redemande.',
  'N\'y compte pas.', 'Ma réponse est non.', 'Mes sources disent non.', 'Les perspectives ne sont pas terribles.', 'Très peu probable.',
];

export const JOKES = [
  ['Pourquoi les plongeurs plongent-ils toujours en arrière ?', 'Parce que sinon ils tombent dans le bateau.'],
  ['Que dit un escargot quand il croise une limace ?', '« Regarde, un nudiste ! »'],
  ['Quel est le comble pour un électricien ?', 'De ne pas être au courant.'],
  ['Pourquoi les poissons détestent l\'ordinateur ?', 'À cause du Net.'],
  ['Comment appelle-t-on un chat tombé dans un pot de peinture le jour de Noël ?', 'Un chat-peint de Noël.'],
  ['Qu\'est-ce qui est jaune et qui attend ?', 'Jonathan.'],
  ['Pourquoi les développeurs confondent Halloween et Noël ?', 'Parce que OCT 31 = DEC 25.'],
  ['Que fait une fraise sur un cheval ?', 'Tagada tagada.'],
  ['Quel est le sport le plus fruité ?', 'La boxe : on s\'y prend des pêches et on tombe dans les pommes.'],
  ['Pourquoi le livre de maths est triste ?', 'Parce qu\'il a trop de problèmes.'],
  ['Comment appelle-t-on un boomerang qui ne revient pas ?', 'Un bâton.'],
  ['Que dit une imprimante dans l\'eau ?', 'J\'ai papier.'],
  ['Quel est le comble pour un jardinier ?', 'De raconter des salades.'],
  ['Pourquoi les vaches ferment-elles les yeux pendant la traite ?', 'Pour faire du lait concentré.'],
  ['Qu\'est-ce qu\'un canif ?', 'Un petit fien.'],
  ['Pourquoi le squelette ne va-t-il pas à la fête ?', 'Parce qu\'il n\'a personne avec qui y aller… il n\'a pas de corps.'],
  ['Comment les abeilles communiquent-elles ?', 'Par e-miel.'],
  ['Que dit un zéro à un huit ?', '« Jolie ceinture ! »'],
  ['Quel est le fruit préféré des profs d\'histoire ?', 'Les dattes.'],
  ['Pourquoi les fantômes sont-ils de mauvais menteurs ?', 'Parce qu\'on voit à travers eux.'],
  ['Comment appelle-t-on un chien sans pattes ?', 'On ne l\'appelle pas, on va le chercher.'],
  ['Quel est le comble pour un plombier ?', 'D\'en avoir ras la cuvette… et de ne jamais trouver la fuite de ses idées.'],
  ['Pourquoi Napoléon n\'a-t-il jamais déménagé ?', 'Parce qu\'il avait un bon appart.'],
  ['Qu\'est-ce qui est vert et qui monte et qui descend ?', 'Un petit pois dans un ascenseur.'],
  ['Pourquoi les programmeurs préfèrent le mode sombre ?', 'Parce que la lumière attire les bugs.'],
  ['Que dit un citron qui fait un braquage ?', '« Plus un zeste ! »'],
  ['Comment fait-on pour allumer un barbecue breton ?', 'On utilise des breizh.'],
  ['Quelle est la femelle du hamster ?', 'L\'amsterdam.'],
  ['Pourquoi les maths sont-elles tristes à la plage ?', 'Parce qu\'elles ont trop de sinus.'],
  ['Que se passe-t-il quand deux poissons s\'énervent ?', 'Le thon monte.'],
];

export const FACTS = [
  'Les poulpes ont trois cœurs et un sang bleu.',
  'Le miel ne se périme pas : on a retrouvé du miel comestible dans des tombes égyptiennes.',
  'Une journée sur Vénus dure plus longtemps qu\'une année sur Vénus.',
  'Les bananes sont légèrement radioactives à cause de leur potassium 40.',
  'La tour Eiffel peut grandir d\'une quinzaine de centimètres en été à cause de la dilatation.',
  'Les loutres de mer se tiennent la main en dormant pour ne pas dériver.',
  'Le cœur d\'une crevette se trouve dans sa tête.',
  'Il y a plus d\'arbres sur Terre que d\'étoiles dans la Voie lactée (environ 3 000 milliards contre 100 à 400 milliards).',
  'Les flamants roses sont roses grâce aux pigments de leur nourriture.',
  'Un éclair est environ cinq fois plus chaud que la surface du Soleil.',
  'Le mot « robot » vient du tchèque « robota », qui signifie travail forcé.',
  'Les vaches ont des meilleures amies et stressent quand on les sépare.',
  'La Grande Muraille de Chine n\'est pas visible à l\'œil nu depuis l\'espace.',
  'Les dauphins se donnent des « noms » sous forme de sifflements uniques.',
  'Un escargot peut dormir jusqu\'à trois ans.',
  'Les empreintes de langue sont uniques, comme les empreintes digitales.',
  'Le premier bug informatique était un vrai papillon de nuit coincé dans un relais (1947).',
  'Les pieuvres peuvent goûter avec leurs ventouses.',
  'Oxford est plus ancienne que l\'Empire aztèque.',
  'Les chats passent environ 70 % de leur vie à dormir.',
  'La France est le pays qui compte le plus de fuseaux horaires (12, avec l\'outre-mer).',
  'L\'ADN humain est identique à environ 60 % à celui d\'une banane.',
  'Les étoiles de mer n\'ont pas de cerveau.',
  'Le Mont Everest grandit d\'environ 4 mm par an.',
  'Les koalas dorment jusqu\'à 22 heures par jour.',
  'Il faut environ 8 minutes et 20 secondes à la lumière du Soleil pour atteindre la Terre.',
  'Les girafes n\'ont que sept vertèbres cervicales, comme les humains.',
  'Le « # » s\'appelle un croisillon, pas un dièse.',
  'Un nuage cumulus moyen pèse environ 500 tonnes.',
  'Les abeilles peuvent reconnaître des visages humains.',
  'Le Sahara était une savane verdoyante il y a environ 6 000 ans.',
  'Les hippopotames sécrètent une substance rougeâtre qui agit comme crème solaire.',
];

export const WYR = [
  ['Pouvoir voler', 'Pouvoir être invisible'],
  ['Ne plus jamais manger de pizza', 'Ne plus jamais manger de chocolat'],
  ['Vivre sans musique', 'Vivre sans films ni séries'],
  ['Parler toutes les langues', 'Parler aux animaux'],
  ['Voyager dans le passé', 'Voyager dans le futur'],
  ['Avoir toujours trop chaud', 'Avoir toujours trop froid'],
  ['Être célèbre', 'Être riche mais inconnu'],
  ['Ne plus jamais utiliser Internet', 'Ne plus jamais prendre l\'avion'],
  ['Lire dans les pensées', 'Voir l\'avenir 10 secondes à l\'avance'],
  ['Vivre à la montagne', 'Vivre au bord de la mer'],
  ['Avoir un dragon', 'Être un dragon'],
  ['Toujours dire ce que tu penses', 'Ne plus jamais pouvoir parler'],
  ['Jouer uniquement à un seul jeu vidéo à vie', 'Ne plus jamais jouer à un jeu vidéo'],
  ['Te téléporter où tu veux', 'Arrêter le temps 1 heure par jour'],
  ['Manger épicé à chaque repas', 'Manger sans sel à chaque repas'],
  ['Avoir un bouton pause dans la vie', 'Avoir un bouton retour arrière'],
  ['Être le meilleur joueur d\'une équipe nulle', 'Être le pire joueur d\'une équipe géniale'],
  ['Vivre dans un monde sans nuit', 'Vivre dans un monde sans jour'],
  ['Ne boire que de l\'eau', 'Ne boire que du soda'],
  ['Connaître la date de ta mort', 'Connaître la cause de ta mort'],
  ['Explorer l\'espace', 'Explorer les abysses'],
  ['Avoir un super-pouvoir inutile', 'Aucun super-pouvoir'],
  ['Être un sorcier à Poudlard', 'Être un Jedi'],
  ['Vivre sans téléphone', 'Vivre sans ordinateur'],
  ['Revivre ta meilleure journée en boucle', 'Découvrir chaque jour quelque chose de nouveau'],
  ['Parler comme un pirate pour toujours', 'Chanter au lieu de parler pour toujours'],
  ['Avoir 10 chats', 'Avoir 3 chiens'],
  ['Gagner au loto', 'Trouver l\'amour de ta vie'],
  ['Être coincé dans un ascenseur avec ton ex', 'Être coincé avec ton patron'],
  ['Avoir une mémoire parfaite', 'Pouvoir oublier ce que tu veux'],
];

export const ROASTS = [
  '{user}, tu es la preuve que l\'évolution peut faire marche arrière.',
  '{user}, si l\'ignorance était une énergie renouvelable, tu alimenterais tout le pays.',
  '{user}, ton wifi a plus de personnalité que toi.',
  '{user}, tu es comme un nuage : quand tu pars, la journée s\'éclaircit.',
  '{user}, même Google ne trouve pas l\'intérêt de tes messages.',
  '{user}, tu as le charisme d\'une chaise pliante.',
  '{user}, tu serais en retard à ton propre anniversaire surprise.',
  '{user}, ta photo de profil est la meilleure chose chez toi… et elle est floue.',
  '{user}, tu fais des fautes d\'orthographe même dans les emojis.',
  '{user}, tu joues comme si ta manette était débranchée.',
  '{user}, tu es la raison pour laquelle les shampooings ont un mode d\'emploi.',
  '{user}, si tu étais un légume, tu serais une endive : personne ne te choisit en premier.',
  '{user}, tu as deux neurones et ils se battent pour la troisième place.',
  '{user}, ton humour est comme une mise à jour Windows : long et inutile.',
  '{user}, tu es tellement lent que les escargots te doublent en klaxonnant.',
  '{user}, même ton reflet fait semblant de ne pas te connaître.',
  '{user}, tu as l\'énergie d\'une batterie à 1 % sans chargeur.',
  '{user}, tu cuisines tellement mal que les pompiers te connaissent par ton prénom.',
  '{user}, ton sens de l\'orientation ferait pleurer un GPS.',
  '{user}, tu es le « ctrl + z » que personne n\'a demandé.',
  '{user}, tu es comme un lundi matin : personne ne t\'attend avec impatience.',
  '{user}, tes blagues ont besoin d\'une notice explicative.',
  '{user}, tu as le talent caché d\'être toujours du mauvais côté de la conversation.',
  '{user}, tu es le tutoriel qu\'on passe toujours.',
  '{user}, tu es tellement ennuyeux que même tes pensées baillent.',
];

export const HANGMAN_WORDS = {
  animaux: ['ELEPHANT', 'GIRAFE', 'KANGOUROU', 'CROCODILE', 'PAPILLON', 'HERISSON', 'PINGOUIN', 'DAUPHIN', 'ECUREUIL', 'CAMELEON', 'HIPPOPOTAME', 'RHINOCEROS', 'SCORPION', 'TORTUE', 'LEOPARD', 'MARMOTTE'],
  pays: ['FRANCE', 'BRESIL', 'JAPON', 'CANADA', 'AUSTRALIE', 'ARGENTINE', 'NORVEGE', 'PORTUGAL', 'MEXIQUE', 'EGYPTE', 'INDONESIE', 'ISLANDE', 'MAROC', 'VIETNAM', 'SUISSE', 'BELGIQUE'],
  fruits: ['ANANAS', 'FRAMBOISE', 'MANGUE', 'PASTEQUE', 'MYRTILLE', 'CLEMENTINE', 'ABRICOT', 'GROSEILLE', 'POMELO', 'MIRABELLE', 'NECTARINE', 'GRENADE', 'BANANE', 'CERISE'],
  metiers: ['BOULANGER', 'POMPIER', 'ASTRONAUTE', 'CHIRURGIEN', 'ARCHITECTE', 'JOURNALISTE', 'PLOMBIER', 'VETERINAIRE', 'MENUISIER', 'PHOTOGRAPHE', 'BIBLIOTHECAIRE', 'INFIRMIER'],
  informatique: ['ALGORITHME', 'PROCESSEUR', 'NAVIGATEUR', 'SERVEUR', 'CLAVIER', 'PYTHON', 'JAVASCRIPT', 'COMPILATEUR', 'ROUTEUR', 'DISCORD', 'BASEDEDONNEES', 'PAREFEU', 'ORDINATEUR', 'LINUX'],
  objets: ['PARAPLUIE', 'BOUSSOLE', 'TELESCOPE', 'ESCALIER', 'ACCORDEON', 'TROMPETTE', 'LAMPADAIRE', 'HORLOGE', 'CASSEROLE', 'TOBOGGAN', 'SABLIER', 'BOUGIE'],
};

export const TRIVIA_CATEGORIES = { culture: '🧠 Culture générale', histoire: '📜 Histoire', geo: '🌍 Géographie', sciences: '🔬 Sciences', sport: '⚽ Sport', ecrans: '🎬 Cinéma & musique', jeux: '🎮 Jeux vidéo', info: '💻 Informatique' };

/** a[0] = bonne réponse ; d = difficulté (1 à 3). */
export const TRIVIA = [
  { c: 'culture', d: 1, q: 'Combien de côtés a un hexagone ?', a: ['6', '5', '7', '8'] },
  { c: 'culture', d: 1, q: 'Qui a peint « La Joconde » ?', a: ['Léonard de Vinci', 'Michel-Ange', 'Raphaël', 'Botticelli'] },
  { c: 'culture', d: 1, q: 'Qui a écrit « Les Misérables » ?', a: ['Victor Hugo', 'Émile Zola', 'Honoré de Balzac', 'Alexandre Dumas'] },
  { c: 'culture', d: 1, q: 'Combien de jours compte une année bissextile ?', a: ['366', '365', '364', '367'] },
  { c: 'culture', d: 1, q: 'Quelle est la monnaie du Japon ?', a: ['Le yen', 'Le yuan', 'Le won', 'La roupie'] },
  { c: 'culture', d: 2, q: 'Combien de cordes possède une guitare classique ?', a: ['6', '4', '5', '7'] },
  { c: 'culture', d: 1, q: 'Quel est l\'animal terrestre le plus rapide ?', a: ['Le guépard', 'Le lion', 'L\'antilope', 'Le lévrier'] },
  { c: 'culture', d: 2, q: 'Quelle langue compte le plus de locuteurs natifs au monde ?', a: ['Le mandarin', 'L\'anglais', 'L\'espagnol', 'L\'hindi'] },
  { c: 'culture', d: 1, q: 'Qui a écrit « Le Petit Prince » ?', a: ['Antoine de Saint-Exupéry', 'Jules Verne', 'Albert Camus', 'Marcel Pagnol'] },
  { c: 'histoire', d: 1, q: 'En quelle année a eu lieu la prise de la Bastille ?', a: ['1789', '1792', '1776', '1804'] },
  { c: 'histoire', d: 1, q: 'Qui fut le premier empereur des Français ?', a: ['Napoléon Ier', 'Louis XIV', 'Charlemagne', 'Napoléon III'] },
  { c: 'histoire', d: 1, q: 'En quelle année l\'être humain a-t-il marché sur la Lune pour la première fois ?', a: ['1969', '1965', '1972', '1959'] },
  { c: 'histoire', d: 2, q: 'Quelle civilisation a bâti le Machu Picchu ?', a: ['Les Incas', 'Les Aztèques', 'Les Mayas', 'Les Olmèques'] },
  { c: 'histoire', d: 1, q: 'Quel mur est tombé en novembre 1989 ?', a: ['Le mur de Berlin', 'Le mur d\'Hadrien', 'La Grande Muraille', 'Le mur des Lamentations'] },
  { c: 'histoire', d: 1, q: 'Quel roi était surnommé « le Roi-Soleil » ?', a: ['Louis XIV', 'Louis XVI', 'François Ier', 'Henri IV'] },
  { c: 'histoire', d: 1, q: 'En quelle année a débuté la Première Guerre mondiale ?', a: ['1914', '1918', '1912', '1939'] },
  { c: 'histoire', d: 2, q: 'Quelle reine d\'Égypte fut l\'alliée de Jules César puis de Marc Antoine ?', a: ['Cléopâtre VII', 'Néfertiti', 'Hatchepsout', 'Néfertari'] },
  { c: 'histoire', d: 2, q: 'Dans quelle ville Jeanne d\'Arc a-t-elle été brûlée ?', a: ['Rouen', 'Orléans', 'Reims', 'Paris'] },
  { c: 'geo', d: 2, q: 'Quelle est la capitale de l\'Australie ?', a: ['Canberra', 'Sydney', 'Melbourne', 'Perth'] },
  { c: 'geo', d: 1, q: 'Quel est le plus long fleuve de France ?', a: ['La Loire', 'La Seine', 'Le Rhône', 'La Garonne'] },
  { c: 'geo', d: 1, q: 'Quel est le plus grand océan du monde ?', a: ['L\'océan Pacifique', 'L\'océan Atlantique', 'L\'océan Indien', 'L\'océan Arctique'] },
  { c: 'geo', d: 3, q: 'Avec combien de pays la France métropolitaine partage-t-elle une frontière terrestre ?', a: ['8', '6', '7', '9'] },
  { c: 'geo', d: 1, q: 'Quel est le plus haut sommet du monde ?', a: ['L\'Everest', 'Le K2', 'Le Kilimandjaro', 'Le mont Blanc'] },
  { c: 'geo', d: 2, q: 'Quelle est la capitale du Canada ?', a: ['Ottawa', 'Toronto', 'Montréal', 'Vancouver'] },
  { c: 'geo', d: 2, q: 'Dans quel pays se trouve Tombouctou ?', a: ['Le Mali', 'Le Niger', 'La Mauritanie', 'Le Sénégal'] },
  { c: 'geo', d: 1, q: 'Quel est le plus grand désert chaud du monde ?', a: ['Le Sahara', 'Le Gobi', 'Le Kalahari', 'L\'Atacama'] },
  { c: 'geo', d: 1, q: 'Quel pays a la plus grande superficie ?', a: ['La Russie', 'Le Canada', 'La Chine', 'Les États-Unis'] },
  { c: 'sciences', d: 1, q: 'Quel est le symbole chimique de l\'or ?', a: ['Au', 'Ag', 'Or', 'Go'] },
  { c: 'sciences', d: 1, q: 'Quelle planète est la plus proche du Soleil ?', a: ['Mercure', 'Vénus', 'Mars', 'La Terre'] },
  { c: 'sciences', d: 2, q: 'Combien d\'os compte le squelette d\'un adulte ?', a: ['206', '186', '226', '256'] },
  { c: 'sciences', d: 2, q: 'Quel gaz est le plus abondant dans l\'atmosphère terrestre ?', a: ['L\'azote', 'L\'oxygène', 'Le dioxyde de carbone', 'L\'argon'] },
  { c: 'sciences', d: 2, q: 'Quelle est approximativement la vitesse de la lumière dans le vide ?', a: ['300 000 km/s', '150 000 km/s', '1 000 000 km/s', '30 000 km/s'] },
  { c: 'sciences', d: 1, q: 'Qui a formulé la théorie de la relativité ?', a: ['Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Marie Curie'] },
  { c: 'sciences', d: 1, q: 'Quelle est la formule chimique de l\'eau ?', a: ['H₂O', 'CO₂', 'O₂', 'H₂O₂'] },
  { c: 'sciences', d: 2, q: 'Quel organe produit l\'insuline ?', a: ['Le pancréas', 'Le foie', 'Les reins', 'La rate'] },
  { c: 'sciences', d: 1, q: 'Quelle est la plus grande planète du système solaire ?', a: ['Jupiter', 'Saturne', 'Neptune', 'Uranus'] },
  { c: 'sport', d: 1, q: 'Combien de joueurs une équipe de football aligne-t-elle sur le terrain ?', a: ['11', '10', '12', '9'] },
  { c: 'sport', d: 1, q: 'Quel pays a remporté la Coupe du monde de football 2018 ?', a: ['La France', 'La Croatie', 'La Belgique', 'Le Brésil'] },
  { c: 'sport', d: 1, q: 'Quel tournoi du Grand Chelem se joue sur terre battue ?', a: ['Roland-Garros', 'Wimbledon', 'L\'US Open', 'L\'Open d\'Australie'] },
  { c: 'sport', d: 2, q: 'Combien de points vaut un essai au rugby à XV ?', a: ['5', '3', '4', '7'] },
  { c: 'sport', d: 1, q: 'Quelle ville a accueilli les Jeux olympiques d\'été 2024 ?', a: ['Paris', 'Los Angeles', 'Tokyo', 'Londres'] },
  { c: 'sport', d: 3, q: 'Combien de minutes dure le temps réglementaire d\'un match NBA ?', a: ['48', '40', '60', '45'] },
  { c: 'sport', d: 1, q: 'Quel sport pratique Teddy Riner ?', a: ['Le judo', 'La lutte', 'La boxe', 'Le karaté'] },
  { c: 'sport', d: 1, q: 'De quelle couleur est le maillot du leader du Tour de France ?', a: ['Jaune', 'Vert', 'À pois', 'Blanc'] },
  { c: 'ecrans', d: 1, q: 'Qui a réalisé le film « Titanic » (1997) ?', a: ['James Cameron', 'Steven Spielberg', 'Martin Scorsese', 'Ridley Scott'] },
  { c: 'ecrans', d: 2, q: 'Dans quel film Star Wars Dark Vador révèle-t-il « Je suis ton père » ?', a: ['L\'Empire contre-attaque', 'Un nouvel espoir', 'Le Retour du Jedi', 'La Menace fantôme'] },
  { c: 'ecrans', d: 1, q: 'Quel groupe a chanté « Bohemian Rhapsody » ?', a: ['Queen', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'] },
  { c: 'ecrans', d: 1, q: 'Quel célèbre compositeur est devenu sourd ?', a: ['Beethoven', 'Mozart', 'Bach', 'Chopin'] },
  { c: 'ecrans', d: 1, q: 'Quel jeune sorcier porte une cicatrice en forme d\'éclair ?', a: ['Harry Potter', 'Ron Weasley', 'Drago Malefoy', 'Neville Londubat'] },
  { c: 'ecrans', d: 1, q: 'Quel film Pixar met en scène un rat qui rêve d\'être chef cuisinier ?', a: ['Ratatouille', 'Le Monde de Nemo', 'Là-haut', 'Coco'] },
  { c: 'ecrans', d: 1, q: 'Qui a chanté « La Vie en rose » ?', a: ['Édith Piaf', 'Dalida', 'Barbara', 'Juliette Gréco'] },
  { c: 'ecrans', d: 1, q: 'Combien de films compte la trilogie « Le Seigneur des anneaux » de Peter Jackson ?', a: ['3', '2', '4', '6'] },
  { c: 'jeux', d: 1, q: 'Quel plombier est la mascotte de Nintendo ?', a: ['Mario', 'Luigi', 'Wario', 'Toad'] },
  { c: 'jeux', d: 1, q: 'Dans Minecraft, quelle créature verte explose ?', a: ['Le Creeper', 'Le Zombie', 'L\'Enderman', 'Le Squelette'] },
  { c: 'jeux', d: 1, q: 'Quelle entreprise fabrique la PlayStation ?', a: ['Sony', 'Nintendo', 'Microsoft', 'Sega'] },
  { c: 'jeux', d: 1, q: 'Comment s\'appelle le héros de « The Legend of Zelda » ?', a: ['Link', 'Zelda', 'Ganon', 'Epona'] },
  { c: 'jeux', d: 3, q: 'En quelle année est sorti Pac-Man ?', a: ['1980', '1985', '1978', '1990'] },
  { c: 'jeux', d: 1, q: 'Quel jeu de Riot Games oppose deux équipes de cinq champions ?', a: ['League of Legends', 'Dota 2', 'Smite', 'Overwatch'] },
  { c: 'jeux', d: 1, q: 'Quel hérisson bleu est la mascotte de Sega ?', a: ['Sonic', 'Tails', 'Knuckles', 'Shadow'] },
  { c: 'jeux', d: 2, q: 'Quel studio français a créé la série Assassin\'s Creed ?', a: ['Ubisoft', 'Quantic Dream', 'Arkane', 'Dontnod'] },
  { c: 'info', d: 1, q: 'Que signifie l\'acronyme « HTML » ?', a: ['HyperText Markup Language', 'High Text Machine Language', 'HyperTool Multi Language', 'Home Tool Markup Language'] },
  { c: 'info', d: 1, q: 'Qui a fondé Microsoft avec Paul Allen ?', a: ['Bill Gates', 'Steve Jobs', 'Linus Torvalds', 'Mark Zuckerberg'] },
  { c: 'info', d: 1, q: 'Combien de bits compte un octet ?', a: ['8', '4', '16', '10'] },
  { c: 'info', d: 1, q: 'Quel langage s\'exécute nativement dans les navigateurs web ?', a: ['JavaScript', 'Python', 'C++', 'Rust'] },
  { c: 'info', d: 2, q: 'Qui a créé le noyau Linux ?', a: ['Linus Torvalds', 'Richard Stallman', 'Dennis Ritchie', 'Ken Thompson'] },
  { c: 'info', d: 2, q: 'Quel est le port par défaut du protocole HTTPS ?', a: ['443', '80', '22', '8080'] },
  { c: 'info', d: 1, q: 'Que signifie « CPU » ?', a: ['Central Processing Unit', 'Computer Personal Unit', 'Central Power Unit', 'Core Processing Utility'] },
  { c: 'info', d: 2, q: 'Combien vaut le nombre binaire 1010 en décimal ?', a: ['10', '8', '12', '5'] },
];

/** Modèles memegen.link courants (repli si l'API /templates est indisponible). */
export const MEME_TEMPLATES_FALLBACK = [
  { id: 'drake', name: 'Drake Hotline Bling', lines: 2 }, { id: 'db', name: 'Distracted Boyfriend', lines: 3 }, { id: 'buzz', name: 'X, X Everywhere', lines: 2 },
  { id: 'doge', name: 'Doge', lines: 2 }, { id: 'fry', name: 'Futurama Fry', lines: 2 }, { id: 'fine', name: 'This is Fine', lines: 2 },
  { id: 'gru', name: 'Gru\'s Plan', lines: 4 }, { id: 'ds', name: 'Daily Struggle', lines: 3 }, { id: 'cmm', name: 'Change My Mind', lines: 1 },
  { id: 'pigeon', name: 'Is This a Pigeon?', lines: 3 }, { id: 'rollsafe', name: 'Roll Safe', lines: 2 }, { id: 'spongebob', name: 'Mocking Spongebob', lines: 2 },
  { id: 'wonka', name: 'Condescending Wonka', lines: 2 }, { id: 'harold', name: 'Hide the Pain Harold', lines: 2 }, { id: 'astronaut', name: 'Always Has Been', lines: 4 },
  { id: 'mordor', name: 'One Does Not Simply', lines: 2 }, { id: 'success', name: 'Success Kid', lines: 2 }, { id: 'stonks', name: 'Stonks', lines: 2 },
  { id: 'cheems', name: 'Cheems', lines: 2 }, { id: 'both', name: 'Why Not Both?', lines: 2 }, { id: 'aag', name: 'Ancient Aliens Guy', lines: 2 },
  { id: 'kermit', name: 'But That\'s None of My Business', lines: 2 }, { id: 'exit', name: 'Left Exit 12 Off Ramp', lines: 3 }, { id: 'right', name: 'Anakin and Padme', lines: 4 },
];
