/** Contenus intégrés des jeux de salon (utilisés en complément des contenus ajoutés par le serveur). */

export const QOTD_DEFAULTS = [
  'Quel est le meilleur conseil que tu aies jamais reçu ?', 'Si tu pouvais vivre dans n\'importe quel pays, lequel choisirais-tu et pourquoi ?',
  'Quel est le jeu vidéo qui t\'a le plus marqué ?', 'Quel super-pouvoir aimerais-tu avoir ?', 'Quel est ton plat préféré de tous les temps ?',
  'Quelle compétence aimerais-tu apprendre cette année ?', 'Quel film pourrais-tu regarder en boucle ?', 'Quel est ton plus beau souvenir de vacances ?',
  'Si tu pouvais dîner avec une personnalité (vivante ou non), qui choisirais-tu ?', 'Quelle est la chanson que tu écoutes le plus en ce moment ?',
  'Quel métier rêvais-tu de faire quand tu étais enfant ?', 'Plutôt lever tôt ou couche-tard ? Pourquoi ?', 'Quel livre recommanderais-tu à tout le monde ?',
  'Quelle est ta plus grande fierté ?', 'Quelle invention trouves-tu la plus utile ?', 'Quel est ton endroit préféré pour te détendre ?',
  'Si tu gagnais au loto demain, quelle serait ta première dépense ?', 'Quel est le talent caché que personne ne te connaît ?', 'Quelle série as-tu dévorée récemment ?',
  'Chat ou chien ? Défends ton camp !', 'Quelle époque historique aimerais-tu visiter ?', 'Quel est ton emoji le plus utilisé ?',
  'Quelle est la chose la plus étrange que tu aies mangée ?', 'Quel est ton rituel du matin ?', 'Quelle application ne pourrais-tu pas supprimer de ton téléphone ?',
  'Quel objet emporterais-tu sur une île déserte ?', 'Quel est le meilleur jeu de société selon toi ?', 'Qu\'est-ce qui te fait rire à coup sûr ?',
  'Quelle saison préfères-tu et pourquoi ?', 'Quel est ton personnage de fiction préféré ?', 'Si tu pouvais maîtriser une langue instantanément, laquelle ?',
  'Quelle est ta boisson chaude préférée ?', 'Quel a été ton premier ordinateur ou ta première console ?', 'Quel défi aimerais-tu relever ?',
  'Quel est le meilleur concert ou spectacle auquel tu aies assisté ?', 'Quelle habitude aimerais-tu prendre ?', 'Quel est ton snack de gaming idéal ?',
  'Si tu étais un animal, lequel serais-tu ?', 'Quelle est la plus belle ville que tu aies visitée ?', 'Quel conseil donnerais-tu à ton toi d\'il y a 10 ans ?',
  'Quel est le dernier truc qui t\'a rendu vraiment heureux ?', 'Mer ou montagne ?',
];

export const TRUTHS = [
  'Quelle est la chose la plus embarrassante qui te soit arrivée en public ?', 'Quel est ton plus gros mensonge (inoffensif) ?', 'Quelle est ta plus grande peur ?',
  'Quel est le dernier message que tu as envoyé ?', 'As-tu déjà fait semblant d\'aimer un cadeau ?', 'Quelle est ta pire habitude ?',
  'Quel est le surnom le plus ridicule qu\'on t\'ait donné ?', 'As-tu déjà ri à un moment totalement inapproprié ?', 'Quelle est la dernière chose que tu as googlée ?',
  'Quel est ton plaisir coupable musical ?', 'As-tu déjà accusé quelqu\'un d\'autre pour une bêtise que tu avais faite ?', 'Quel est ton rêve le plus bizarre ?',
  'Quelle est la chose la plus folle que tu aies faite pour quelqu\'un ?', 'Quel talent inutile possèdes-tu ?', 'Quelle est ta pire note à un examen ?',
  'As-tu déjà dormi en cours ou au travail ?', 'Quel est le film qui t\'a fait pleurer ?', 'Quelle est la chose la plus chère que tu aies cassée ?',
  'Quelle célébrité t\'a déjà fait craquer ?', 'Quel est ton pire fail en jeu vidéo ?', 'Combien de temps as-tu passé sur ton téléphone hier ?',
  'Quel est le dernier mensonge que tu as dit ?', 'Quelle est ta plus grosse bêtise d\'enfance ?', 'Quelle est l\'appli que tu ouvres le plus ?',
  'As-tu déjà envoyé un message à la mauvaise personne ?', 'Quelle est la chanson que tu chantes sous la douche ?', 'Quel est ton plus grand regret ?',
  'Quel est le pire cadeau que tu aies reçu ?', 'Qui sur ce serveur te fait le plus rire ?', 'Quel secret de cuisine caches-tu ?',
];

export const DARES = [
  'Écris ta prochaine phrase uniquement en emojis.', 'Change ton pseudo pour « Patate cosmique » pendant 10 minutes.', 'Envoie un compliment sincère à la dernière personne qui a parlé.',
  'Écris un haïku sur le serveur.', 'Parle comme un pirate pendant tes 3 prochains messages.', 'Raconte une blague nulle.',
  'Envoie le 7e GIF qui apparaît quand tu cherches « chat ».', 'Fais une déclaration d\'amour à ta pizza préférée.', 'Écris ton prénom avec ton coude et poste le résultat.',
  'Décris ta journée comme un commentateur sportif.', 'Invente un slogan pour le serveur.', 'Écris un message sans utiliser la lettre « e ».',
  'Poste une photo de l\'objet le plus proche de toi.', 'Fais une critique gastronomique de ton dernier repas.', 'Imite ton personnage de jeu vidéo préféré en 2 phrases.',
  'Écris un poème de 4 vers sur ta chaise.', 'Parle à la troisième personne pendant 5 minutes.', 'Donne un surnom affectueux à chaque personne en ligne.',
  'Chante (par écrit) le refrain de la dernière chanson que tu as écoutée.', 'Écris une fausse critique 5 étoiles pour une chaussette.', 'Envoie ton emoji préféré 10 fois.',
  'Fais un mini-discours de remerciement comme si tu avais gagné un Oscar.', 'Invente une nouvelle règle absurde pour le serveur.', 'Réponds uniquement par des questions pendant 3 messages.',
  'Écris le titre du film de ta vie.', 'Explique le fonctionnement d\'un grille-pain comme si c\'était de la haute technologie.', 'Complimente le bot de façon exagérée.',
  'Raconte ton week-end idéal en 3 emojis.', 'Écris une mini-histoire qui commence par « Il était une fois une licorne fatiguée ».', 'Tape ton prochain message les yeux fermés.',
];

export const THIS_OR_THAT = [
  ['Pizza', 'Burger'], ['Chat', 'Chien'], ['Mer', 'Montagne'], ['Été', 'Hiver'], ['Café', 'Thé'], ['Films', 'Séries'], ['PC', 'Console'], ['Matin', 'Soir'],
  ['Sucré', 'Salé'], ['Livre', 'Film'], ['Ville', 'Campagne'], ['Voyager dans le passé', 'Voyager dans le futur'], ['Voler', 'Être invisible'],
  ['Netflix', 'YouTube'], ['Chocolat noir', 'Chocolat au lait'], ['Pâtes', 'Riz'], ['Marvel', 'DC'], ['Star Wars', 'Star Trek'], ['Android', 'iPhone'],
  ['Crêpes', 'Gaufres'], ['Douche', 'Bain'], ['Plage', 'Piscine'], ['Texto', 'Appel'], ['Pluie', 'Neige'], ['Train', 'Avion'], ['Fromage', 'Dessert'],
  ['Rap', 'Rock'], ['Jeux solo', 'Jeux multi'], ['Mario', 'Sonic'], ['Minecraft', 'Fortnite'], ['Sushi', 'Tacos'], ['Frites', 'Potatoes'],
  ['Lire l\'avenir', 'Lire les pensées'], ['Chaud', 'Froid'], ['Lundi', 'Vendredi'], ['Dormir', 'Manger'], ['Clavier mécanique', 'Clavier silencieux'],
  ['Mode sombre', 'Mode clair'], ['Chaussettes dépareillées', 'Chaussettes assorties'], ['Pain au chocolat', 'Chocolatine'], ['Glace', 'Gâteau'], ['Zombies', 'Aliens'],
];

export const QUOTES = [
  ['La vie, c\'est comme une bicyclette, il faut avancer pour ne pas perdre l\'équilibre.', 'Albert Einstein'],
  ['Le succès n\'est pas final, l\'échec n\'est pas fatal : c\'est le courage de continuer qui compte.', 'Winston Churchill'],
  ['Il n\'y a qu\'une façon d\'échouer, c\'est d\'abandonner avant d\'avoir réussi.', 'Georges Clemenceau'],
  ['Le bonheur est parfois caché dans l\'inconnu.', 'Victor Hugo'],
  ['On ne voit bien qu\'avec le cœur. L\'essentiel est invisible pour les yeux.', 'Antoine de Saint-Exupéry'],
  ['Choisissez un travail que vous aimez et vous n\'aurez pas à travailler un seul jour de votre vie.', 'Confucius'],
  ['La simplicité est la sophistication suprême.', 'Léonard de Vinci'],
  ['Ils ne savaient pas que c\'était impossible, alors ils l\'ont fait.', 'Mark Twain'],
  ['Le plus grand risque est de ne prendre aucun risque.', 'Mark Zuckerberg'],
  ['Qui veut faire quelque chose trouve un moyen, qui ne veut rien faire trouve une excuse.', 'Proverbe arabe'],
  ['La créativité, c\'est l\'intelligence qui s\'amuse.', 'Albert Einstein'],
  ['Un voyage de mille lieues commence toujours par un premier pas.', 'Lao Tseu'],
  ['L\'imagination est plus importante que le savoir.', 'Albert Einstein'],
  ['Rien ne se perd, rien ne se crée, tout se transforme.', 'Antoine Lavoisier'],
  ['Le doute est le commencement de la sagesse.', 'Aristote'],
  ['Ce n\'est pas parce que les choses sont difficiles que nous n\'osons pas, c\'est parce que nous n\'osons pas qu\'elles sont difficiles.', 'Sénèque'],
  ['La patience est amère, mais son fruit est doux.', 'Jean-Jacques Rousseau'],
  ['Il faut toujours viser la lune, car même en cas d\'échec, on atterrit dans les étoiles.', 'Oscar Wilde'],
  ['Soyez vous-même, les autres sont déjà pris.', 'Oscar Wilde'],
  ['Le talent gagne des matchs, mais le travail d\'équipe gagne des championnats.', 'Michael Jordan'],
  ['La seule façon de faire du bon travail est d\'aimer ce que vous faites.', 'Steve Jobs'],
  ['L\'échec est l\'opportunité de recommencer de façon plus intelligente.', 'Henry Ford'],
  ['Le pessimiste se plaint du vent, l\'optimiste espère qu\'il va changer, le réaliste ajuste ses voiles.', 'William Arthur Ward'],
  ['Hier est derrière, demain est un mystère, et aujourd\'hui est un cadeau.', 'Eleanor Roosevelt'],
  ['Tout ce que nous sommes est le résultat de ce que nous avons pensé.', 'Bouddha'],
  ['Ce qui ne me tue pas me rend plus fort.', 'Friedrich Nietzsche'],
  ['La connaissance s\'acquiert par l\'expérience, tout le reste n\'est que de l\'information.', 'Albert Einstein'],
  ['Le secret pour avancer, c\'est de commencer.', 'Mark Twain'],
  ['Agis comme s\'il était impossible d\'échouer.', 'Dorothea Brande'],
  ['Le rire est le soleil qui chasse l\'hiver du visage humain.', 'Victor Hugo'],
  ['La musique donne une âme à nos cœurs et des ailes à la pensée.', 'Platon'],
  ['On ne naît pas femme, on le devient.', 'Simone de Beauvoir'],
  ['Il faut cultiver notre jardin.', 'Voltaire'],
  ['Je pense, donc je suis.', 'René Descartes'],
  ['L\'homme est condamné à être libre.', 'Jean-Paul Sartre'],
  ['La lecture est à l\'esprit ce que l\'exercice est au corps.', 'Joseph Addison'],
  ['Le cœur a ses raisons que la raison ne connaît point.', 'Blaise Pascal'],
  ['Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours.', 'Gandhi'],
  ['Sois le changement que tu veux voir dans le monde.', 'Gandhi'],
  ['Il n\'est jamais trop tard pour devenir ce que nous aurions pu être.', 'George Eliot'],
  ['La persévérance est le chemin du succès.', 'Charlie Chaplin'],
  ['Un problème sans solution est un problème mal posé.', 'Albert Einstein'],
];
